name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: docs
  BUILD_DIR: .vitepress/dist

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # ---------- build ----------
      - name: Setup node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "20"
          cache: "yarn"
      - name: Install requirements
        run: yarn install
      - name: Build
        run: yarn build
      # ---------- publish ----------
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}

  create-index:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "5s"

      - uses: actions/checkout@v4
      - name: Index vitepress
        run: |
          docker run \
            -e APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }} \
            -e API_KEY=${{ secrets.ALGOLIA_API_KEY }} \
            -e "CONFIG=$(cat algolia-config.json | jq -r tostring)" \
            algolia/docsearch-scraper
